//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cotas_planos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cotas_planos()
        {
            this.Plano = new HashSet<Plano>();
        }
    
        public int id_cota_plano { get; set; }
        public Nullable<int> id_tipo { get; set; }
        public Nullable<double> Toleracia_max { get; set; }
        public Nullable<double> Toleracia_min { get; set; }
        public Nullable<int> id_maquina { get; set; }
        public Nullable<double> Valor_Cota { get; set; }
        public Nullable<int> id_operacion { get; set; }
    
        public virtual Diccionario_odfm Diccionario_odfm { get; set; }
        public virtual Plano_operaciones Plano_operaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Plano> Plano { get; set; }
    }
}
