//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lineas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lineas()
        {
            this.Producto = new HashSet<Producto>();
        }
    
        public int id_linea { get; set; }
        public string CodigoLinea { get; set; }
        public Nullable<int> fk_Norma { get; set; }
        public Nullable<int> fk_Imagen { get; set; }
    
        public virtual DiccionarioDeFabricacion DiccionarioDeFabricacion { get; set; }
        public virtual Imagenes Imagenes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Producto> Producto { get; set; }
    }
}
