//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ODF_MATRICERIA
    {
        public int id_odfmat { get; set; }
        public string odfm_codigo { get; set; }
        public Nullable<System.DateTime> Fecha_creacion { get; set; }
        public Nullable<bool> Estado { get; set; }
        public int id_usuarioOrden { get; set; }
        public Nullable<int> id_pano { get; set; }
        public string obs { get; set; }
    
        public virtual Plano Plano { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
    }
}
