//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class odfm_insumos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public odfm_insumos()
        {
            this.Plano_operaciones = new HashSet<Plano_operaciones>();
        }
    
        public int id_insumo { get; set; }
        public Nullable<int> id_operacion { get; set; }
        public Nullable<int> AceroCalidad { get; set; }
    
        public virtual Diccionario_odfm Diccionario_odfm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Plano_operaciones> Plano_operaciones { get; set; }
    }
}
