//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Of_tecnica_Cod_planos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Of_tecnica_Cod_planos()
        {
            this.Plano = new HashSet<Plano>();
        }
    
        public int id_codplanos { get; set; }
        public Nullable<int> id_seccion { get; set; }
        public Nullable<int> Num_mac { get; set; }
        public Nullable<int> Num_rev_plan { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<int> UsuarioCreador { get; set; }
    
        public virtual Diccionario_odfm Diccionario_odfm { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Plano> Plano { get; set; }
    }
}
