//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plano
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Plano()
        {
            this.ODF_MATRICERIA = new HashSet<ODF_MATRICERIA>();
            this.Plano_operaciones = new HashSet<Plano_operaciones>();
        }
    
        public int ID_PLANO { get; set; }
        public byte[] Img { get; set; }
        public Nullable<int> id_codplanos { get; set; }
        public Nullable<int> id_cotas { get; set; }
    
        public virtual Cotas_planos Cotas_planos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ODF_MATRICERIA> ODF_MATRICERIA { get; set; }
        public virtual Of_tecnica_Cod_planos Of_tecnica_Cod_planos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Plano_operaciones> Plano_operaciones { get; set; }
    }
}
