//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnidadesOdf
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UnidadesOdf()
        {
            this.Lote = new HashSet<Lote>();
        }
    
        public int Id_unidad { get; set; }
        public Nullable<int> id_lote { get; set; }
        public Nullable<int> Nombre { get; set; }
        public Nullable<int> Producto { get; set; }
        public Nullable<double> PesoUnidad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lote> Lote { get; set; }
        public virtual Producto Producto1 { get; set; }
        public virtual Productos Productos { get; set; }
    }
}
